"""Initial migration.

Revision ID: e688a0d1fcd9
Revises: 7dae3d4988b4
Create Date: 2025-01-19 08:26:28.482615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e688a0d1fcd9'
down_revision = '7dae3d4988b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=128), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
